image: 'Visual Studio 2017'

configuration:
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - C:\msys64\usr\bin\bash -lc "cd \"%APPVEYOR_BUILD_FOLDER%\" && scripts/appveyor.sh"

artifacts:
  - path: Chiaki
    name: Chiaki

deploy:
  description: 'Chiaki Binaries'
  provider: GitHub
  auth_token:
    secure: Amvzm3PMM5nv+iFsqaU7TZ9fgyYt/YIrOLV0QMiCyOoUlLRIaiYxWiJ7maTpxhZ9
  artifact: "Chiaki"
  on:
    appveyor_repo_tag: true

